### ISSUE TITLE
Single population nodes as circles, not pies

### ISSUE THREAD

**Issue by fdchevalier** [grunwaldlab/poppr#201]
Hi Zhian,

First, thanks for developing this useful package.

When making networks, nodes representing one population (but not necessarily one sample) are displayed as pies. This is not very aesthetic and could even be misleading because the pie might suggest presence of a second population.

Here is a minimal reproducible example (tested with the `master` and the `devel` branches).

```R
library(poppr)
data(Aeut)
adist <- diss.dist(Aeut, percent = TRUE)
amsn <- poppr.msn(Aeut, adist, showplot = FALSE)

plot_poppr_msn(Aeut, amsn, gadj = 15, inds="NA")
```

Another illustration of this can be found on [StackOverflow](https://stackoverflow.com/q/27438905).

I found a way to make single population pie as circle. This involved modification of the `msn_handlers.R` file on the `master` branch. But I noticed that this file does not exist anymore on the `devel` branch. In this case, modifications need to be done in the `visualizations.r` file.

Anyway, I made modifications on both branches. They can be reviewed [here](https://github.com/fdchevalier/poppr/commit/02dfaa901e21289a652d2ef6f451393e0642b960) and [here](https://github.com/fdchevalier/poppr/commit/e677318e7c22c6787f02a64e4db83abf80271528) and tested with the minimal example above.

If you find this useful, please let me know what branch needs to be merged.

Fred

**Comment by zkamvar** [comment]
Hi @fdchevalier,

Thank you for the report and the solution! **Please do make a pull request (from your changes to the master branch) and I will perform a code review.** 😃 

For reference, I don't use the "devel" branch anymore because it made more sense just to maintain stability on the master branch and then have experiments on separate branches with clear names. Here's the process I strive for: https://github.com/grunwaldlab/poppr/blob/master/CONTRIBUTING.md
