### ISSUE TITLE
Clade rooting abnormally with updated 

### ISSUE THREAD

**Issue by mandiedriskill** [grunwaldlab/poppr#239]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [X ] I have the most recent version of poppr and R
 - [X ] I have found a bug
   - [ X] I have searched for solutions on this site and the [poppr forum](https://groups.google.com/group/poppr)
   - [ X] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------

Hi all,

We are noticing a clade abnormality when I updated from "poppr" version 2.8.6 to version 2.9.0. 

I will give you some background information:
We are visually comparing distinguishability between two different genotyping methods in Humulus and this visualization is done through dendrograms. One dendrogram is from SSR data and the other dendrogram is from KASP SNP bi-allelic data. The issues is with the SNP dendrogram. We have a group of 11 wild North American sample that have identical fingerprints, except for 3 samples have multiple "NA" calls. Because how the SNP probes were designed we know that all 11 samples should have the same fingerprint. Because we have "NA" present in our SNP data set, we used the missing = "ignore" argument within the aboot function (we can send an .Rmd of the code). Before the update we had a clade that had all 11 samples grouped together and a clade with 3 additional samples ("Burlington") that are highly related (see attached Dendrogram before).

<img width="384" alt="Dendrogram before" src="https://user-images.githubusercontent.com/40249599/114219617-c00c4e80-991f-11eb-810c-bf9176da9e54.png">

We ran exactly the same code after an update and now the 3 samples with "NA" values are seperating from the 8 samples that have identicle fingerprints (see attached Dendrogram after). 

<img width="300" alt="Dendrogram after" src="https://user-images.githubusercontent.com/40249599/114220219-90aa1180-9920-11eb-9b7c-4dfc47a3d18a.png">

We have tried graphing the data with different programs (ggtree and plot.phylo), re-rooting the node in mutiple locations, flipping the internal nodes, re-ordering the data, rolling back multiple r packages (poppr, ape, ade4, adegent, ect.). But the odd confirguation of the clade persists. Any help on this would be greatly appreciated. We can send the data privetly as it is not published yet. 

Bests,
The Bassil Lab Team

---------

**Comment by zkamvar** [comment]
I'm not sure what would be causing this. In order to help you solve this, I do need a reproducible example. At the moment, I do not know any of the following information: branch lengths, data type (genind/genlight), genetic distance used, tree algorithm used, version of ape, version of R. Without this information, the best I can do is guess. 

There were only two releases after 2.8.6: a minor release that corrected documentation for CRAN and then https://github.com/grunwaldlab/poppr/releases/tag/v.2.9.0, which did not touch any of the code involved in the bootstrapping. 

I know you've tried rolling back versions of poppr, ape, ade4, and adegenet, but have you tried using the {checkpoint} package to roll back ALL your packages to the last date you did the analysis? https://cran.r-project.org/web/packages/checkpoint/vignettes/checkpoint.html If you upgraded R, have you tried using an older version of R (notably, R 3.6 fixed a bug that biased the core randomization routines, which changed a lot of results)? I've found https://rstudio.cloud particularly helpful in those situations. 

I will also note: I will probably be slow to reply (as you've probably noticed); I voluntarily manage poppr in my free time that is not otherwise dedicated to my own mental wellbeing.

**Comment by mandiedriskill** [comment]
Thanks for following up on this issue.  

Here is the code we used.

`library(poppr)`
`library(ape)`
`library(adegenet)`
`library(ggtree)`
`library(ggplot2)`
`library(gridExtra)`
`library(grid)`

`mydatSNP_R = read.table("./25_KASP_SNP.txt", header = TRUE, stringsAsFactors = FALSE)`

`marker_namesSNP <- colnames(mydatSNP)`
`marker_namesSNP<- marker_namesSNP[4:length(marker_namesSNP)]`
`accession_namesSNP <- mydatSNP[,1]`
`ploidySNP <- as.vector(mydatSNP$Ploidy)`
`allele_datSNP <- mydatSNP[,4:ncol(mydatSNP)]`
`mydat_genindSNP = df2genind(allele_datSNP, sep = ":", ind.names = accession_namesSNP, ploidy = ploidySNP, NA.char = "NA")`

`mytreeSNP = aboot(mydat_genindSNP, 
                  tree = "njs", 
                  sample = 200, 
                  cutoff = 75, 
                  distance = provesti.dist, 
                  quiet = FALSE, 
                  showtree = FALSE, 
                  missing = "ignore")`

`denSNP<-ggtree(mytreeSNP, size=.05)+
  geom_tiplab(size=.5)+
  ggplot2::xlim(NA,1)`


I was not able to recover the original tree created by the "aboot" function, but I was able to recover the tree object before and after the updates. 


[tree_objects.zip](https://github.com/grunwaldlab/poppr/files/6408223/tree_objects.zip)

The tree objects are able to be plotted with {treeio}.

`tree<-treeio::read.jtree(file ="path/tree_obejct")`
`ggtree(tree, size=.05)+
  geom_tiplab(size=.5)+
  ggplot2::xlim(NA,1)`


From the before and after tree objects, we can see the two trees are virtually the same except for the wild North American clade (top clade), which is the clade that is rooting abnormally. If you need the raw data, please let us know and we can send it to you. Thank you for all your help!

**Comment by zkamvar** [comment]
## Summary

Looking at the code, I suspect that the change may have originated in the {ape} package. The layout of the tree represents that of the distance derived from the initial data and the distance function was last updated in 2015, which means that the culprit may be the `ape::njs()` function.

Please try one of the solutions in https://github.com/grunwaldlab/poppr/issues/239#issuecomment-827190581 and raise an issue in https://github.com/emmanuelparadis/ape with information of the versions between the old tree and the new tree. 

Again, the difficulty here is that there are so many unknowns about what your R environment looked like when you got the first result. You've been able to give me the version of {poppr} you were using, but the versions of {ape}, {adegenet}, and R are all important here. Even knowing the date that you last ran the analysis before you updated would help so that versions could be inferred. In the future, it's good practice to use version control and save the output of `sessionInfo()` to give you a snapshot of what your R environment looked like. 

## Why it's not poppr

There are two poppr functions you use, neither of which have been updated recently.

1. `aboot()`, which has [not changed in the last three years](https://github.com/grunwaldlab/poppr/blame/main/R/bootstraping.R#L220-L296)
2. `provesti.dist()`, which was [last modified in 2015, for the 2.0.0 release](https://github.com/grunwaldlab/poppr/blame/main/R/distances.r#L346-L375)

In the process of creating a bootstrapped tree, there are two components necessary: 

1. A distance function (you used `provesti.dist()`)
2. A tree function that uses the matrix output by the distance function to create the base tree (you used `ape::njs()`)

The `aboot()` function is a *wrapper* around the process of creating a bootstrapped tree. It merely orchestrates the coordination between the distance function, the tree function, and `ape::boot.phylo()`. There is one function that manipulates the original tree, and that is `fix_negative_branch()`, which, again [was last updated in 2015](https://github.com/grunwaldlab/poppr/blame/294c2eab512db16b8b68c851725802f33c19e111/R/internal.r#L750-L790)
