### ISSUE TITLE
Feature request: separation/removal of sf package requirement

### ISSUE THREAD

**Issue by alexweisberg** [grunwaldlab/poppr#247]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [ ] I have the most recent version of poppr and R
 - [ ] I have found a bug
   - [ ] I have searched for solutions on this site and the [poppr forum](https://groups.google.com/group/poppr)
   - [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [x] I want to request a new feature

--------
I would like to request the ability to install poppr without the sf package as a requirement to install. This package is very difficult to install as it requires specific versions of the GDAL library as well as several others. It seems this package is primarily for importing GEO and ArcGIS location data, which is a specific use case. Would it be possible to set up poppr so that this is an optional requirement? Thanks!

---------

**Comment by zkamvar** [comment]
Hi @alexweisberg, I'm afraid that this is not really possible at the moment because poppr depends on adegenet, which imports spdep for its spatial functions, which imports sf. To quote @hlapp: "adegenet is downloading half of CRAN!"

We _might_ be able to get spdep as a soft dependency of adegenet specifically for the spatial features, but I know a lot of adegenet users do use the spatial analyses, so I'm not sure how well that would go over :(

**Comment by alexweisberg** [comment]
Hi @zkamvar, thanks for letting me know. I think we'll have to go with setting up a conda environment with everything then. Though that would be nice to have the soft dependency option for adegenet.

**Comment by zkamvar** [comment]
Hi @alexweisberg, I've updated adegenet to no longer require spdep (not yet on CRAN). It's available on my R-universe if you want:

```r
# Enable this universe
options(repos = c(
    zkamvar = 'https://zkamvar.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'))

# Install some packages
install.packages('adegenet')
```
